# *********************************************************************
#
#  Unix Makefile for examples (use  GNU make)
#
# ********************************************************************


xcode4:
	xcodebuild

clean:
	@rm -rf  build

release: xcode4 clean


